
#spring:
#  redis:
#    host: 127.0.0.1
#    database: 0
#    lettuce:
#      pool:
#        max-active: 50
#        max-wait: 10ms
#        max-idle: 50
#        min-idle: 50
#    connect-timeout: 10ms
#    timeout: 1000ms


server:
  port: 11555
  tomcat:
    threads:
      max: 200