spring:
  redis:
    client-type: lettuce
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 8




server:
  port: 11555
  tomcat:
    threads:
      max: 500

logging:
  level:
    io.lettuce.core: ERROR
    org.springframework.web: ERROR
    org.springframework.boot: ERROR
    minssogi.study.rate_limiting.redis: INFO
    org.apache: ERROR
