spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  http2:
    enabled: true
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: root!123
    key-store-type: PKCS12
    key-alias: tomcat
